#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM [OPTIONS] user/repos
-d DIR: change current directory
-u: make github username directory
-r: revert time stamp
";

my %OPT;
getopts('rd:u', \%OPT);

if (@ARGV != 1) {
    print STDERR $USAGE;
    exit 1;
}
my ($USER_REPO) = @ARGV;

if ($OPT{d}) {
    my $dir = $OPT{d};
    if (!-e $dir) {
	mkdir($dir) || die;
    }
    chdir($dir)
}


if ($USER_REPO =~ /^([-\w]+)\/([-\w]+)$/) {
    my ($user, $repo) = ($1, $2);
    if ($OPT{u}) {
	if (!-e $user) {
	    mkdir($user) || die;
	}
	chdir($user) || die;
    }
    system "git clone git\@github.com:$USER_REPO";
    if (-d $repo) {
	chdir($repo) || die;
	if ($OPT{r}) {
	    system "git.revert.timestamp.pl";
	}
    }
} else {
    die $USER_REPO;
}
