#!/usr/bin/perl -w
use strict;
use File::Basename;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM file message ...
git add, commit and push
";

if (@ARGV < 2) {
    print STDERR $USAGE;
    exit 1;
}
my ($FILE, @MESSAGE) = @ARGV;
my $MESSAGE = "@MESSAGE";

print "[add]\n";
system "git add $FILE";
print "\n";

print "[commit]\n";
system "git commit -m '$MESSAGE'";
print "\n";

print "[push]\n";
system "git push";
