#!/usr/bin/perl -w
use strict;
use File::Basename;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM file message ...
git add, commit and push
";

my ($FILE, @MESSAGE) = @ARGV;
my $MESSAGE = "@MESSAGE";

if (@ARGV == 1) {
    $MESSAGE = "update $FILE";
} elsif (@ARGV < 2) {
    print STDERR $USAGE;
    exit 1;
}

system "git fetch origin";
my $diff_exit_code = system("git diff HEAD..FETCH_HEAD --exit-code --quiet") >> 8;
if ($diff_exit_code) {
    print "[pull]\n";
    system "git pull";
    print "\n";
}

print "[add]\n";
system "git add $FILE";
print "\n";

print "[commit]\n";
system "git commit -m '$MESSAGE'";
print "\n";

print "[push]\n";
system "git push";
