#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
use POSIX;
my $PROGRAM = basename $0;
my $USAGE= "Usage: $PROGRAM [options] file
  -b N   beginning of class
  -w N   width of class
  -W N   weight of *
  -n     show only frequencies
  -p     hide percentage
  -j     juxtapose bar and number
";

my %opt;
getopts('njb:w:W:', \%opt);

my $MAX_BAR_HEIGHT = 50;

my (@numbers, $min, $max);
-t && !@ARGV and die $USAGE;
while(<>){
    chomp;
    if (/^-?\d+(\.\d+)?$/) { # integer or decimal (optionally with minus sign)
	if (@numbers) {
	    $_ < $min and $min = $_;
	    $_ > $max and $max = $_;
	} else {
	    ($min, $max) = ($_, $_);
	}
        push(@numbers, $_);
    } else {
	print STDERR "$_: Not a number.\n";
    }
}

# The class width is calculated automatically, by default.
# width = range / ceil(log2(n)+ 1)
my $width = ($max-$min) / ceil(log(@numbers) / log(2) + 1);
if ($width < 1) {
    $width = 0.1;
} else {
    $width = ceil($width);
}
if ($opt{w}) {
    $width = $opt{w};
}
$width ||= 1;

my $begin = floor($min);
if ($begin > 0 && $width < 1) {
    $begin = 0;
}
if (defined $opt{b}) {
    $begin = $opt{b};
}
if ($begin>$max) {
    print STDERR "$begin: Too large value for the beginning of class.\n";
    exit(1);
}

# Determine the length to display representitive numbers
my $max_of_abs = ($max > -$min) ? $max : -$min;
my $num_len = ceil(log10 $max_of_abs) + 1; # one more space for munus sign;
if ($width < 1) {
    $num_len = length(sprintf("%s", $width));
}

# Count frequencies in each class
my @freq;
foreach (@numbers) {
    $freq[int(($_-$begin)/$width)]++;
}
for (my $i=0; $i<@freq; $i++) {
    if (! $freq[$i]) {
	$freq[$i] = 0;
    }
}

# Determine the length to display frequencies
my $max_freq = $freq[0];
foreach (@freq) {
    $_ > $max_freq and $max_freq = $_;
}
my $freq_len=ceil(log10 $max_freq);
# Determine how many frequencies a asterisk represents
my $waster = $opt{W} || ceil($max_freq/$MAX_BAR_HEIGHT);


# Print summary of input data
print("total freqency = ",$#numbers+1,"\n");
printf("min   = %${num_len}s\n",$min);
printf("max   = %${num_len}s\n",$max);
printf("width = %${num_len}s\n",$width);

# print("total frequency = ",$#numbers+1,"\n");
# print("min = $min, ");
# print("max = $max\n");
# print("class width = $width\n");

# print("total_frequency=", $#numbers+1, ", ");
# print "min=$min, max=$max, ";
# print "width=$width, ";
# print "\n";


# Print frequency destribution.
my $cum = 0;
my $repres=$begin;
if ($opt{n}) {
    # If -n option is spesified, print only frequencies.
    foreach (@freq) {
	$cum += $_;
	printf("%${num_len}d-: %${freq_len}d %5.1f%% %5.1f%%\n", $repres, $_, $_/@numbers*100, $cum/@numbers*100);
	$repres += $width;
    }
    printf("%${num_len}d :\n", $repres);
} else {
    print(" " x ($num_len + 4), "*:$waster\n");
    foreach (@freq) {
	$cum += $_;
	my $naster = ceil($_/$waster);

	# Print freqency and percentage
        if ($width < 1) {
            my $after_point = $num_len - 2;
            printf("%.${after_point}f- |", $repres);
        } else {
            printf("%${num_len}s- |", $repres);
        }
	print '*'x $naster;
	if (!$opt{j}) {
	    print ' 'x ($MAX_BAR_HEIGHT - $naster + 1);
	    if (!$opt{p}) {
		printf("%${freq_len}d",$_) if $_;
		printf(" %5.1f%% %5.1f%%", $_/@numbers*100, $cum/@numbers*100) if $_;
	    }
	} else {
	    printf("%d",$_) if $_;
	    if (!$opt{p}) {
		print ' 'x ($MAX_BAR_HEIGHT + floor(log10 $max_freq) - ($naster + floor(log10 $_)));
		printf(" %5.1f%% %5.1f%%", $_/@numbers*100 ,$cum/@numbers*100) if $_;
	    }
	}

	print("\n");
	$repres += $width;
    }
    printf("%${num_len}s  |\n", $repres);
}
