#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM
-a: all files
-p: show permission info
-u: show user info
-g: show group info
-b: show file size (in bytes)
-s: show file size (human readable)
-f: show full info
-D: show only directory
-d: show directory first
-l: follow symbolic links
-t: show time
-r: sort by time
-N N: limit file numbers
-L L: limit levels
-v: verbose
-c: classical format
-h: help
";

my %OPT;
getopts('apugbsfDdltrN:L:vch', \%OPT);
if ($OPT{h}) {
    print STDERR $USAGE;
    exit(1);
}

my $OPTIONS = '-F';

if ($OPT{a}) {
    $OPTIONS .= ' -a';
}
if ($OPT{p}) {
    $OPTIONS .= ' -p';
}
if ($OPT{u}) {
    $OPTIONS .= ' -pu';
}
if ($OPT{g}) {
    $OPTIONS .= ' -pug';
}
if ($OPT{b}) {
    $OPTIONS .= ' -s --du';
}
if ($OPT{s}) {
    $OPTIONS .= ' -h --du';
}
if ($OPT{f}) {
    $OPTIONS .= ' -pugh --du';
}

if ($OPT{D}) {
    $OPTIONS .= ' -d'
}
if ($OPT{d}) {
    $OPTIONS .= ' --dirsfirst';
}

if ($OPT{l}) {
    $OPTIONS .= ' -l';
}

if ($OPT{t}) {
    $OPTIONS .= ' --timefmt "%Y-%m-%d %H:%M"';
}
if ($OPT{r}) {
    $OPTIONS .= ' --timefmt "%Y-%m-%d %H:%M" -t';
}

if ($OPT{N}) {
    $OPTIONS .= " --filelimit $OPT{N}";
}
if ($OPT{L}) {
    $OPTIONS .= " -L $OPT{L}";
}

if ($OPT{v}) {
} else {
    $OPTIONS .= ' --noreport';
}

if ($OPT{c}) {
    system "tree $OPTIONS @ARGV | less";
} else {
    system "tree -A $OPTIONS @ARGV | less -r";
}
