#!/usr/bin/env python3
import ftplib
from datetime import datetime

def list_ftp_directory(host, username, password, directory):
    ftp = ftplib.FTP(host)
    ftp.login(username, password)
    ftp.cwd(directory)
    
    files = ftp.mlsd()

    for file in files:
        filename = file[0]
        filetime = file[1]["modify"]
        type = file[1]["type"]
        size = file[1]["size"]
        if type == "dir":
            filename += "/"
        print(size, datetime.strptime(filetime, "%Y%m%d%H%M%S"), filename , sep="\t")
    
    ftp.quit()

host = "ftp.ncbi.nlm.nih.gov"
username = "anonymous"
password = ""
directory = "/"

def main():
    list_ftp_directory(host, username, password, directory)

if __name__ == "__main__":
    main()
