#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
# use IPC::Open3;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM FILE
";

my %OPT;
getopts('v', \%OPT);

if (!@ARGV) {
    print STDERR $USAGE;
    exit 1;
}
my $FILE = shift @ARGV;

if (! -e $FILE) {
    die "ERROR: $FILE: $!";
}

my $DIR = "";
my $BINARY_FILE = "";
if ($FILE =~ /^(.+)\.nim$/) {
    my $prefix = $1;
    my $DIR = dirname($prefix);
    my $basename = basename($prefix);
    if ($^O eq "linux") {
        $DIR .= "/linux";
    } elsif ($^O eq "darwin") {
        $DIR .= "/mac"
    } elsif ($^O eq "dos") {
        $DIR .= "/win"
    } else {
        die;
    }
    if (! -e $DIR) {
        mkdir($DIR);
    }
    $BINARY_FILE = "$DIR/$basename";
} else {
    die $USAGE;
}

if ($OPT{v}) {
    system "nim compile --run --out:$BINARY_FILE $FILE";
} elsif (-f $BINARY_FILE && (stat $BINARY_FILE)[9] > (stat $FILE)[9]) {
    system "$BINARY_FILE @ARGV";
} else {
    my $result = `nim compile --out:$BINARY_FILE $FILE 2>&1`;
    if ($? >> 8) {
        print STDERR $result;
        exit($? >> 8);
    }
    system "$BINARY_FILE @ARGV";
}
exit;

my ($EXEC_FILE, $NIM_FILE) = get_exec_file($FILE);
print "$EXEC_FILE, $NIM_FILE\n";

if (! -f $EXEC_FILE && ! -f $NIM_FILE) {
    print STDERR "ERROR: cannot find $EXEC_FILE nor $NIM_FILE\n";
    exit 1;
} elsif ($OPT{v}) {
    system "nim compile --run $FILE @ARGV";
} elsif (-f $EXEC_FILE && ! -f $NIM_FILE ||
	 -f $EXEC_FILE && -f $NIM_FILE && (stat $EXEC_FILE)[9] > (stat $NIM_FILE)[9]) {
    system "$EXEC_FILE @ARGV";
} else {
    my $result = `nim compile $FILE 2>&1`;
    if ($? >> 8) {
	print STDERR $result;
	exit($? >> 8);
    }
    system "$EXEC_FILE @ARGV";
}

################################################################################
### Function ###################################################################
################################################################################

sub get_exec_file {
    my ($file) = @_;
    
    my $prefix = "";
    if ($file =~ /^(.+)\.nim$/) {
        $prefix = $1;
    } else {
        $prefix = $file;
    }

    my $dirname = dirname($prefix);
    my $basename = basename($prefix);
    print "$dirname $basename\n";

    my $exec_file = "";
    if ($prefix =~ /^\//) {
        $exec_file = $prefix;
    } else {
        $exec_file = "./$prefix";
    }

    my $nim_file = "$prefix.nim";

    return ("$exec_file", $nim_file);
}
