#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM [-d] FILE.nim
-d: debug
";

my %OPT;
getopts('d', \%OPT);

if (!@ARGV) {
    print STDERR $USAGE;
    exit 1;
}
my $NIM_FILE = shift @ARGV;

if (! -e $NIM_FILE) {
    die "ERROR: $NIM_FILE: $!";
}

my $DIR = "";
my $BINARY_FILE = "";
if ($NIM_FILE =~ /^(.+)\.nim$/) {
    my $prefix = $1;
    my $DIR = dirname($prefix);
    my $basename = basename($prefix);
    if ($^O eq "linux") {
        $DIR .= "/linux";
    } elsif ($^O eq "darwin") {
        $DIR .= "/mac"
    } elsif ($^O eq "dos") {
        $DIR .= "/win"
    } else {
        die;
    }
    if (! -e $DIR) {
        mkdir($DIR);
    }
    $BINARY_FILE = "$DIR/$basename";
} else {
    print STDERR $USAGE;
    exit(1)
}

if ($OPT{d}) {
    system "nim compile --run --out:$BINARY_FILE $NIM_FILE";
} elsif (-f $BINARY_FILE && (stat $BINARY_FILE)[9] > (stat $NIM_FILE)[9]) {
    system "$BINARY_FILE @ARGV";
} else {
    my $result = `nim compile --out:$BINARY_FILE $NIM_FILE 2>&1`;
    if ($? >> 8) {
        print STDERR $result;
        exit($? >> 8);
    }
    system "$BINARY_FILE @ARGV";
}
