#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM
-l: list servers
";

my %OPT;
getopts('lN:S:Vvn:S:s:1', \%OPT);

my $COMMAND = "$ENV{HOME}/github/sivel/speedtest-cli/speedtest.py";
if (!-f $COMMAND) {
    system "github -prh sivel/speedtest-cli";
}

if ($OPT{l}) {
    system "$COMMAND --list";
    exit;
}

if ($OPT{N}) {
    system "$COMMAND --list | grep -iw '$OPT{N}'";
    exit;
}

my ($NUMBER, $DESCRIPTION);
if ($OPT{S}) {
    $NUMBER = $OPT{S};
    $DESCRIPTION = select_server($NUMBER);
} else {
    # ($NUMBER, $DESCRIPTION) = extract_server("OPEN Project .*");
    ($NUMBER, $DESCRIPTION) = extract_server(".*Tokyo.*");
}

### Testing
if ($OPT{V}) {
    system "$COMMAND --server $NUMBER";
} elsif ($OPT{s} || $OPT{n}) {
    my $sleep_seconds = $OPT{s} || 0;
    printf "Date       Time      %-11s%-15sUpload\n", "Ping", "Download";
    my $count = 0;
    while (1) {
        my $date_time = `date '+%F %T'`;
        chomp($date_time);
        my @line = `$COMMAND --server $NUMBER --simple`;
        printf "$date_time  %-11s%-15s%s\n", extract_speed(@line);
        sleep $sleep_seconds;
        $count ++;
        if ($OPT{n}) {
            if ($OPT{n} == $count) {
                last;
            }
        }
    }
} else {
    if ($OPT{v}) {
        print "Server:   $DESCRIPTION\n";
    }
    my $date_time = `date '+%F %T'`;
    chomp($date_time);
    print "$date_time\n";
    my @line = `$COMMAND --server $NUMBER --simple`;
    my ($ping, $upload, $download) = extract_speed(@line);

    printf "Ping     %9s\n", $ping;
    printf "Download %13s\n", $download;
    printf "Upload   %13s\n", $upload;
}

################################################################################
### Functions ##################################################################
################################################################################
sub extract_speed {
    my @line = @_;
    
    my ($ping, $download, $upload);
    for my $line (@line) {
        if ($line =~ /^Ping: (.*)/) {
            $ping = $1;
        } elsif ($line =~ /^Download: (.*)/) {
            $download = $1;
        } elsif ($line =~ /^Upload: (.*)/) {
            $upload = $1;
        }
    }

    return ($ping, $download, $upload);
}

sub extract_server {
    my ($pattern) = @_;
    
    my @list = `$COMMAND --list 2>&1`;

    my $number = "";
    my $description = "";
    for my $server (@list) {
        if ($server =~ /^\s*(\d+)\) +($pattern)/) {
            $number = $1;
            $description = $2;
            last;
        }
    }

    if ($number !~ /^\d+$/) {
        die @list;
    }

    return ($number, $description);
}

sub select_server {
    my ($number) = @_;
    
    my @list = `$COMMAND --list 2>&1`;

    my $description = "";
    for my $server (@list) {
        if ($server =~ /^\s*$number\) +(\S.*)/) {
            $description = $1;
            last;
        }
    }

    if ($description eq "") {
        die @list;
    }

    return ($description);
}
