#!/usr/bin/perl -w
use strict;
use File::Basename;
use Getopt::Std;
my $PROGRAM = basename $0;
my $USAGE=
"Usage: $PROGRAM
-L LIMIT: limit lines to read
-i
";

my %OPT;
getopts('L:i', \%OPT);

my @M = ();

!@ARGV && -t and die $USAGE;
my $i = 0;
while (<>) {
    chomp;
    my @x = split(/\t/, $_);
    for (my $j=0; $j<@x; $j++) {
	$M[$i][$j] = $x[$j];
    }
    $i ++;
    if ($OPT{L} && $i > $OPT{L} - 1) {
        last;
    }
}

# for (my $i=0; $i<@M; $i++) {
#     for (my $j=0; $j<@{$M[0]}; $j++) {
# 	print $M[$i][$j];
# 	print "\t";
#     }
#     print "\n";
# }

for (my $j=0; $j<@{$M[0]}; $j++) {
    my @line = ();
    if ($OPT{i}) {
        push @line, $j;
    }
    for (my $i=0; $i<@M; $i++) {
# 	if (defined $M[$i][$j]) {
	    push @line, $M[$i][$j];
# 	}
    }
    print join("\t", @line), "\n";
}
